export enum CareerFamily {
  STEM_TECH = 'STEM_TECH',
  CREATIVE_MEDIA = 'CREATIVE_MEDIA',
  EDUCATION_HELPING = 'EDUCATION_HELPING',
  SKILLED_ACTION = 'SKILLED_ACTION',
  BUSINESS_LEADERSHIP = 'BUSINESS_LEADERSHIP',
}
